package br.com.unisales.cadautomoveis.visao;

import br.com.unisales.cadautomoveis.modelo.Codigo;
import br.com.unisales.cadautomoveis.modelo.Pessoa;
import br.com.unisales.cadautomoveis.persistencia.BancoDados;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.dizitart.no2.FindOptions;
import org.dizitart.no2.NitriteId;
import org.dizitart.no2.SortOrder;
import org.dizitart.no2.objects.filters.ObjectFilters;

public class FrmPessoas extends javax.swing.JDialog {

 public Pessoa pessoa = new Pessoa();
 public List<Pessoa> listaPessoas = new LinkedList<>();

 public void buscaPessoas(String nomeCpfPesquisa) {
  String nomeCpfPesq = (nomeCpfPesquisa != null) ? nomeCpfPesquisa : "";
  listaPessoas = BancoDados.tabelaPessoas.find(
          ObjectFilters.or(
                  ObjectFilters.regex("nome", "(?i)" + nomeCpfPesq + ""),
                  ObjectFilters.regex("cpf", "(?i)" + nomeCpfPesq + ""),
                  ObjectFilters.regex("codigo", "(?i)" + nomeCpfPesq + "")
          ),
          FindOptions.sort("nome", SortOrder.Ascending)).toList();
 }

 public void atualizaTabelaGrafica() {
  DefaultTableModel dtm = (DefaultTableModel) tabelaPessoas.getModel();
  dtm.setRowCount(0);
  for (Pessoa p : listaPessoas) {
   dtm.addRow(new Object[]{p.id, p.nome, p.cpf, p.codigo});
  }
 }

 /**
  * busca uma pessoa no banco de dados pelo CPF
  *
  * @param cpf
  * @return
  */
 public Pessoa selecionaPessoaComCPF(String cpf) {
  List<Pessoa> listaCPF = BancoDados.tabelaPessoas
          .find(ObjectFilters.eq("cpf", cpf)).toList();
  if (listaCPF != null && listaCPF.size() > 0) {
   return listaCPF.get(0);
  }
  return null;
 }

 /**
  * verifica se uma pessoa possui automóvel
  *
  * @param pessoa
  * @return
  */
 public boolean ehProprietario(Pessoa pessoa) {
  List listaProps = BancoDados.tabelaAutomoveis.find(
          ObjectFilters.eq("proprietario.id", pessoa.id)
  ).toList();
  return listaProps != null && listaProps.size() > 0;
 }

 public void limpaCampos() {
  edtCPF.setText("");
  edtNome.setText("");
  edtNome.requestFocus();
 }

 public FrmPessoas(java.awt.Frame parent, boolean modal) {
  super(parent, modal);
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jPanel1 = new javax.swing.JPanel();
  jLabel1 = new javax.swing.JLabel();
  edtNome = new javax.swing.JTextField();
  jLabel2 = new javax.swing.JLabel();
  edtCPF = new javax.swing.JFormattedTextField();
  jButton1 = new javax.swing.JButton();
  jButton4 = new javax.swing.JButton();
  jButton5 = new javax.swing.JButton();
  jScrollPane2 = new javax.swing.JScrollPane();
  tabelaPessoas = new javax.swing.JTable();
  jPanel2 = new javax.swing.JPanel();
  edtNomeProcura = new javax.swing.JTextField();
  jLabel3 = new javax.swing.JLabel();
  jButton2 = new javax.swing.JButton();
  jButton3 = new javax.swing.JButton();

  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
  setTitle("Pessoas");
  addWindowListener(new java.awt.event.WindowAdapter() {
   public void windowOpened(java.awt.event.WindowEvent evt) {
    formWindowOpened(evt);
   }
  });

  jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));

  jLabel1.setText("Nome:");

  jLabel2.setText("CPF");

  try {
   edtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
  } catch (java.text.ParseException ex) {
   ex.printStackTrace();
  }

  jButton1.setText("Salvar");
  jButton1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton1ActionPerformed(evt);
   }
  });

  jButton4.setText("Cancela");
  jButton4.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton4ActionPerformed(evt);
   }
  });

  jButton5.setText("Excluir");
  jButton5.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton5ActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(edtNome)
     .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addGroup(jPanel1Layout.createSequentialGroup()
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel1)
       .addComponent(jLabel2)
       .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGap(0, 39, Short.MAX_VALUE))
     .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );
  jPanel1Layout.setVerticalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel2)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jButton1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jButton4)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jButton5)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  tabelaPessoas.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {

   },
   new String [] {
    "Id", "Nome", "CPF", "Código"
   }
  ) {
   boolean[] canEdit = new boolean [] {
    false, false, false, false
   };

   public boolean isCellEditable(int rowIndex, int columnIndex) {
    return canEdit [columnIndex];
   }
  });
  tabelaPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    tabelaPessoasMouseClicked(evt);
   }
  });
  tabelaPessoas.addKeyListener(new java.awt.event.KeyAdapter() {
   public void keyReleased(java.awt.event.KeyEvent evt) {
    tabelaPessoasKeyReleased(evt);
   }
  });
  jScrollPane2.setViewportView(tabelaPessoas);
  if (tabelaPessoas.getColumnModel().getColumnCount() > 0) {
   tabelaPessoas.getColumnModel().getColumn(0).setMinWidth(0);
   tabelaPessoas.getColumnModel().getColumn(0).setPreferredWidth(0);
   tabelaPessoas.getColumnModel().getColumn(0).setMaxWidth(0);
  }

  jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));

  edtNomeProcura.addKeyListener(new java.awt.event.KeyAdapter() {
   public void keyReleased(java.awt.event.KeyEvent evt) {
    edtNomeProcuraKeyReleased(evt);
   }
  });

  jLabel3.setText("Digite nome ou CPF para pesquisa");

  jButton2.setText("Pesquisar");
  jButton2.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton2ActionPerformed(evt);
   }
  });

  jButton3.setText("Limpar pesquisa");
  jButton3.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton3ActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
  jPanel2.setLayout(jPanel2Layout);
  jPanel2Layout.setHorizontalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addComponent(jLabel3)
      .addGap(0, 0, Short.MAX_VALUE))
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addComponent(edtNomeProcura, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    .addContainerGap())
  );
  jPanel2Layout.setVerticalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel3)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(edtNomeProcura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addComponent(jButton2)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(jButton3)))
    .addContainerGap(55, Short.MAX_VALUE))
  );

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(jScrollPane2)
     .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(0, 0, Short.MAX_VALUE))
     .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );

  pack();
  setLocationRelativeTo(null);
 }// </editor-fold>//GEN-END:initComponents

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  //preencho os atributos da pessoa
  pessoa.nome = edtNome.getText();
  pessoa.cpf = edtCPF.getText();

  //pesquisa por CPF
  Pessoa pessoaTesteCPF = selecionaPessoaComCPF(pessoa.cpf);

  if (pessoaTesteCPF == null && pessoa.id == null) {
   //faz a inserção no banco de dados
   pessoa.codigo = "" + BancoDados.getNextCode("Pessoa").valorSequencia;
   BancoDados.tabelaPessoas.insert(pessoa);
  } else if (pessoaTesteCPF == null || pessoaTesteCPF.id.equals(pessoa.id)) {
   //faz a atualização no banco de dados
   BancoDados.tabelaPessoas.update(pessoa);
  } else {
   JOptionPane.showMessageDialog(null, "Não pode cadastrar CPF igual");
   return;
  }

  JOptionPane.showMessageDialog(null, "Dados salvos");
  pessoa = new Pessoa();
  limpaCampos();
  buscaPessoas("");
  atualizaTabelaGrafica();
 }//GEN-LAST:event_jButton1ActionPerformed

 private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  buscaPessoas("");
  atualizaTabelaGrafica();
 }//GEN-LAST:event_formWindowOpened

 private void tabelaPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPessoasMouseClicked
  int linhaSelecionada = tabelaPessoas.getSelectedRow();
  if (linhaSelecionada >= 0) {
   DefaultTableModel dtm = (DefaultTableModel) tabelaPessoas.getModel();
   pessoa = new Pessoa();
   pessoa.id = (NitriteId) dtm.getValueAt(linhaSelecionada, 0);
   /*pessoa.nome = (String) dtm.getValueAt(linhaSelecionada, 1);
   pessoa.cpf = (String) dtm.getValueAt(linhaSelecionada, 2);*/

   pessoa = BancoDados.tabelaPessoas.getById(pessoa.id);
   edtNome.setText(pessoa.nome);
   edtCPF.setText(pessoa.cpf);
  }
 }//GEN-LAST:event_tabelaPessoasMouseClicked

 private void tabelaPessoasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaPessoasKeyReleased
  tabelaPessoasMouseClicked(null);
 }//GEN-LAST:event_tabelaPessoasKeyReleased

 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  String nomePesquisa = edtNomeProcura.getText();
  buscaPessoas(nomePesquisa);
  atualizaTabelaGrafica();
 }//GEN-LAST:event_jButton2ActionPerformed

 private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  edtNomeProcura.setText("");
  buscaPessoas("");
  atualizaTabelaGrafica();
 }//GEN-LAST:event_jButton3ActionPerformed

 private void edtNomeProcuraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNomeProcuraKeyReleased
  jButton2ActionPerformed(null);
 }//GEN-LAST:event_edtNomeProcuraKeyReleased

 private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  limpaCampos();
  pessoa = new Pessoa();
 }//GEN-LAST:event_jButton4ActionPerformed

 private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  if (pessoa.id != null) {
   //verifica se possui automovel como proprietário
   if (ehProprietario(pessoa)) {
    JOptionPane.showMessageDialog(null, "É proprietário!");
    //sai do método
    return;
   }

   int confirma = JOptionPane.showConfirmDialog(null, "Confirma a exclusão?");
   if (confirma == JOptionPane.YES_OPTION) {
    BancoDados.tabelaPessoas.remove(pessoa);
    jButton2ActionPerformed(null);
    limpaCampos();
    pessoa = new Pessoa();
   }
  }
 }//GEN-LAST:event_jButton5ActionPerformed


 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JFormattedTextField edtCPF;
 private javax.swing.JTextField edtNome;
 private javax.swing.JTextField edtNomeProcura;
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JButton jButton3;
 private javax.swing.JButton jButton4;
 private javax.swing.JButton jButton5;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JPanel jPanel2;
 private javax.swing.JScrollPane jScrollPane2;
 private javax.swing.JTable tabelaPessoas;
 // End of variables declaration//GEN-END:variables
}
